# Generated by Django 2.2.7 on 2019-11-22 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20191120_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0, 'must be a postive integer')]),
        ),
    ]
